### ISSUE TITLE
Resources: 

### ISSUE THREAD

**Issue by Ldhatter** [adriannadiaz/Axiona#126]
As a user I want the following as optional resources:
- Financial
- Food Security (Name of Organization, Address, Schedule)
- Job Finding (Name of contact, Email)
- Sexual Health (Address, Phone, Name of Doctor)
- Web Resources (URLS + descriptor)

**Tasks**
- [ ] Discuss with @adriannadiaz the fields
- [ ] Add resources to resource components
- [ ] Make sure it works with case files
- [ ] Frontend tests
- [ ] Backend tests

**Note**
@adriannadiaz  How to avoid a 'Goddess-html-baby'?
