### ISSUE TITLE
Form Generation

### ISSUE THREAD

**Issue by Ldhatter** [adriannadiaz/Axiona#139]
As an admin, I want to be able to customize the application forms and also edit these forms.

This is the EPIC for our form generation strategy.

**Issues**
- [x] Research frontend/components _see issue_ 
- [x] Research backend/storing forms for reuse _see issue_ #140
- [x] After research compare findings and choose strategy and fill upcoming tasks
- [ ] Add new sub-issues ...
